# Generated by Django 6.0 on 2026-01-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='features_product',
            new_name='featured_product',
        ),
    ]
