# Generated by Django 6.0 on 2026-01-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_features_product_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
